import { useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import FadeInSection from "@/components/FadeInSection";
import {
  Brain, Lightbulb, Puzzle, PenTool, TrendingUp, Trophy, Flame,
  Star, Zap, BookOpen, Award, Target, ChevronRight
} from "lucide-react";

const learningZones = [
  {
    id: "knowledge-forge",
    title: "Knowledge Forge",
    desc: "AI helps you understand difficult concepts through simplified explanations and visual learning.",
    icon: Brain,
    color: "from-primary to-secondary",
    glowClass: "hover:shadow-[0_0_30px_hsl(var(--glow-primary))]",
    borderColor: "border-primary/30 hover:border-primary/60",
    topics: ["Science", "Math", "History", "Language"],
  },
  {
    id: "idea-dojo",
    title: "Idea Dojo",
    desc: "A brainstorming space where you generate ideas, project outlines, and creative solutions with AI.",
    icon: Lightbulb,
    color: "from-gold to-accent",
    glowClass: "hover:shadow-[0_0_30px_hsl(var(--glow-gold))]",
    borderColor: "border-gold/30 hover:border-gold/60",
    topics: ["Brainstorm", "Plan", "Outline", "Solve"],
  },
  {
    id: "mind-quest",
    title: "Mind Quest",
    desc: "Interactive logic puzzles and challenges generated by AI to develop critical thinking.",
    icon: Puzzle,
    color: "from-track-teal to-primary",
    glowClass: "hover:shadow-[0_0_30px_hsl(var(--glow-teal))]",
    borderColor: "border-track-teal/30 hover:border-track-teal/60",
    topics: ["Logic", "Patterns", "Riddles", "Strategy"],
  },
  {
    id: "creator-studio",
    title: "Creator Studio",
    desc: "Creative AI tools for stories, diagrams, and visual learning content.",
    icon: PenTool,
    color: "from-track-pink to-secondary",
    glowClass: "hover:shadow-[0_0_30px_hsl(var(--glow-pink))]",
    borderColor: "border-track-pink/30 hover:border-track-pink/60",
    topics: ["Stories", "Diagrams", "Art", "Videos"],
  },
  {
    id: "skill-path",
    title: "Skill Path",
    desc: "A gamified learning progression system showing your XP, levels, achievements, and streaks.",
    icon: TrendingUp,
    color: "from-track-indigo to-primary",
    glowClass: "hover:shadow-[0_0_30px_hsl(var(--glow-indigo))]",
    borderColor: "border-track-indigo/30 hover:border-track-indigo/60",
    topics: ["XP Points", "Levels", "Badges", "Streaks"],
  },
];

const achievements = [
  { icon: "🔥", label: "7-Day Streak", earned: true },
  { icon: "⚡", label: "Speed Learner", earned: true },
  { icon: "🎨", label: "Creative Mind", earned: true },
  { icon: "🧩", label: "Puzzle Master", earned: false },
  { icon: "📚", label: "Bookworm", earned: false },
  { icon: "🏆", label: "Champion", earned: false },
];

const weeklyStats = [
  { day: "Mon", hours: 1.5 },
  { day: "Tue", hours: 2.0 },
  { day: "Wed", hours: 1.0 },
  { day: "Thu", hours: 2.5 },
  { day: "Fri", hours: 1.8 },
  { day: "Sat", hours: 3.0 },
  { day: "Sun", hours: 0.5 },
];

const StudentDashboard = () => {
  const [xp] = useState(2450);
  const [level] = useState(12);
  const maxXp = 3000;

  return (
    <div className="overflow-hidden wave-pattern">
      {/* Dashboard Header */}
      <section className="pt-28 pb-8 bg-section-dark">
        <div className="container mx-auto px-4">
          <FadeInSection>
            <div className="glass-panel p-6 md:p-8 flex flex-col md:flex-row items-center gap-6">
              {/* Avatar */}
              <div className="relative">
                <div className="w-24 h-24 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-4xl shadow-[0_0_30px_hsl(var(--glow-primary))]">
                  🥷
                </div>
                <div className="absolute -bottom-1 -right-1 w-8 h-8 rounded-full bg-gold flex items-center justify-center text-xs font-bold text-gold-foreground shadow-lg">
                  {level}
                </div>
              </div>

              {/* Info */}
              <div className="flex-1 text-center md:text-left">
                <h1 className="font-heading font-bold text-2xl md:text-3xl text-foreground mb-1">
                  Welcome back, <span className="text-gradient-primary">Young Samurai</span>!
                </h1>
                <p className="text-muted-foreground text-sm mb-3">Level {level} · AI Explorer</p>

                {/* XP Bar */}
                <div className="max-w-md">
                  <div className="flex justify-between text-xs text-muted-foreground mb-1">
                    <span className="flex items-center gap-1"><Zap className="w-3 h-3 text-gold" /> {xp} XP</span>
                    <span>{maxXp} XP to Level {level + 1}</span>
                  </div>
                  <div className="w-full h-3 rounded-full bg-muted overflow-hidden">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-primary via-secondary to-gold animate-shimmer"
                      style={{ width: `${(xp / maxXp) * 100}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Stats */}
              <div className="flex gap-6">
                <div className="text-center">
                  <div className="flex items-center justify-center gap-1 text-gold">
                    <Flame className="w-5 h-5" />
                    <span className="font-heading font-bold text-xl">7</span>
                  </div>
                  <p className="text-xs text-muted-foreground">Day Streak</p>
                </div>
                <div className="text-center">
                  <div className="flex items-center justify-center gap-1 text-track-pink">
                    <Trophy className="w-5 h-5" />
                    <span className="font-heading font-bold text-xl">3</span>
                  </div>
                  <p className="text-xs text-muted-foreground">Badges</p>
                </div>
                <div className="text-center">
                  <div className="flex items-center justify-center gap-1 text-track-teal">
                    <Star className="w-5 h-5" />
                    <span className="font-heading font-bold text-xl">24</span>
                  </div>
                  <p className="text-xs text-muted-foreground">Quests Done</p>
                </div>
              </div>
            </div>
          </FadeInSection>
        </div>
      </section>

      {/* Learning Zones */}
      <section className="section-padding bg-section-mid">
        <div className="container mx-auto px-4">
          <FadeInSection>
            <h2 className="heading-section text-center mb-2">
              Learning <span className="text-gradient-primary">Zones</span>
            </h2>
            <p className="text-muted-foreground text-center mb-12">Choose your training ground, young warrior.</p>
          </FadeInSection>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {learningZones.map((zone, i) => (
              <FadeInSection key={zone.id} delay={i * 100}>
                <div className={`glass-panel border-2 ${zone.borderColor} ${zone.glowClass} p-6 transition-all duration-500 cursor-pointer hover:scale-[1.03] h-full group`}>
                  <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${zone.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                    <zone.icon className="w-7 h-7 text-foreground" />
                  </div>
                  <h3 className="font-heading font-bold text-xl text-foreground mb-2">{zone.title}</h3>
                  <p className="text-sm text-muted-foreground mb-4">{zone.desc}</p>
                  <div className="flex flex-wrap gap-2 mb-4">
                    {zone.topics.map((t) => (
                      <span key={t} className="text-xs px-2 py-1 rounded-full bg-muted text-muted-foreground">{t}</span>
                    ))}
                  </div>
                  <div className="flex items-center gap-1 text-primary text-sm font-semibold group-hover:gap-2 transition-all">
                    Enter Zone <ChevronRight className="w-4 h-4" />
                  </div>
                </div>
              </FadeInSection>
            ))}
          </div>
        </div>
      </section>

      {/* Achievements */}
      <section className="section-padding bg-section-dark">
        <div className="container mx-auto px-4">
          <FadeInSection>
            <h2 className="heading-section text-center mb-12">
              Your <span className="text-gradient-primary">Achievements</span>
            </h2>
          </FadeInSection>

          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4 max-w-4xl mx-auto">
            {achievements.map((a, i) => (
              <FadeInSection key={i} delay={i * 80}>
                <div className={`glass-panel p-4 text-center transition-all duration-300 ${
                  a.earned ? "card-gold-glow hover:scale-105" : "opacity-40 grayscale"
                }`}>
                  <div className="text-3xl mb-2">{a.icon}</div>
                  <p className="text-xs text-foreground font-medium">{a.label}</p>
                  {a.earned && <Award className="w-3 h-3 text-gold mx-auto mt-1" />}
                </div>
              </FadeInSection>
            ))}
          </div>
        </div>
      </section>

      {/* Weekly Summary */}
      <section className="section-padding bg-section-mid">
        <div className="container mx-auto px-4 max-w-3xl">
          <FadeInSection>
            <h2 className="heading-section text-center mb-12">
              Weekly <span className="text-gradient-primary">Summary</span>
            </h2>
          </FadeInSection>

          <FadeInSection delay={200}>
            <div className="glass-panel p-8">
              <div className="flex items-end justify-between gap-2 h-40">
                {weeklyStats.map((s, i) => (
                  <div key={i} className="flex-1 flex flex-col items-center gap-1">
                    <span className="text-xs text-muted-foreground">{s.hours}h</span>
                    <div className="w-full rounded-t-lg bg-gradient-to-t from-primary to-secondary transition-all duration-700"
                      style={{ height: `${(s.hours / 3) * 100}%` }}
                    />
                    <span className="text-xs text-muted-foreground">{s.day}</span>
                  </div>
                ))}
              </div>
              <div className="mt-6 flex justify-between text-sm">
                <span className="text-muted-foreground">Total: <span className="text-foreground font-semibold">12.3 hours</span></span>
                <span className="text-muted-foreground">Avg: <span className="text-foreground font-semibold">1.76 hrs/day</span></span>
              </div>
            </div>
          </FadeInSection>
        </div>
      </section>

      {/* Quick Actions */}
      <section className="section-padding bg-section-dark">
        <div className="container mx-auto px-4 max-w-2xl">
          <FadeInSection>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Button variant="hero" size="xl" className="w-full" asChild>
                <Link to="/ai-sensei">🥋 Talk to AI Sensei</Link>
              </Button>
              <Button variant="hero-outline" size="xl" className="w-full" asChild>
                <Link to="/creativity-lab">🎨 Open Creativity Lab</Link>
              </Button>
            </div>
          </FadeInSection>
        </div>
      </section>
    </div>
  );
};

export default StudentDashboard;
